language: php
php:
  - "8.0"
  - "7.4"
  - "7.1"
  - "7.0"
  - "5.6"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
  - DOKUWIKI=old-stable
before_install:
  - "rm .gitignore"
  - "wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh"
  - "wget https://raw.github.com/mark-rushakoff/OpenPhantomScripts/master/phantom-qunit.js -P _test"
install:
  - "mv req-travis.txt requirements.txt"
  - "sh travis.sh"
script:
  - "cd _test && php fetchphpunit.php && php phpunit.phar --stderr --group plugin_siteexport"
#  - "cd ../lib/plugins/siteexport/_test && sh phantomjs/runPhantomJs.sh"
